version: '3.8'
services:
  fileserver:
    image: nginx
    container_name: fileserver
    hostname: fileserver
    restart: always

  nosqldata:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    restart: always

  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    hostname: mabbit
    restart: always

  psql:
    image: postgres:13.3
    container_name: psql
    hostname: psql
    restart: always

  auth-api:
    image: ghcr.io/ferbray/auth-api:latest
    container_name: auth-api
    depends_on:
      - psql
      - rabbitmq

  email-api:
    image: ghcr.io/ferbray/email-api:latest
    container_name: email-api
    depends_on:
      - psql
      - rabbitmq

  game-api:
    image: ghcr.io/ferbray/game-api:latest
    container_name: game-api
    depends_on:
      - psql
      - rabbitmq

  identity-api:
    image: ghcr.io/ferbray/identity-api:latest
    container_name: identity-api
    depends_on:
      - psql
      - rabbitmq

  payment-api:
    image: ghcr.io/ferbray/payment-api:latest
    container_name: payment-api
    depends_on:
      - psql
      - rabbitmq

  promocode-api:
    image: ghcr.io/ferbray/promocode-api:latest
    container_name: promocode-api
    depends_on:
      - psql
      - rabbitmq

  resources-api:
    image: ghcr.io/ferbray/resources-api:latest
    container_name: resources-api
    depends_on:
      - psql
      - rabbitmq

  review-api:
    image: ghcr.io/ferbray/review-api:latest
    container_name: review-api
    depends_on:
      - psql
      - rabbitmq

  statistics-api:
    image: ghcr.io/ferbray/statistics-api:latest
    container_name: statistics-api
    depends_on:
      - psql
      - rabbitmq

  support-api:
    image: ghcr.io/ferbray/support-api:latest
    container_name: support-api
    depends_on:
      - psql
      - rabbitmq

  withdraw-api:
    image: ghcr.io/ferbray/withdraw-api:latest
    container_name: withdraw-api
    depends_on:
      - psql
      - rabbitmq

  gateway-api:
    image: ghcr.io/ferbray/gateway-api:latest
    container_name: gateway-api

volumes:
  database:
  rabbitmq: