version: '3.8'
services:
  fileserver:
    container_name: fileserver
    hostname: fileserver
    image: nginx
    restart: always

  nosqldata:
    container_name: mongodb
    hostname: mongodb
    image: mongo
    restart: always

  rabbitmq:
    container_name: rabbitmq
    hostname: mabbit
    image: rabbitmq:3.10.7-management
    restart: always

  psql:
    container_name: psql
    hostname: psql
    image: postgres:13.3
    restart: always

  auth-api:
    container_name: auth-api
    image: auth-api:1.0.0
    depends_on:
      - psql
      - rabbitmq

  email-api:
    container_name: email-api
    image: email-api:1.0.0
    depends_on:
      - psql
      - rabbitmq

  game-api:
    container_name: game-api
    image: game-api:1.0.0
    depends_on:
      - psql
      - rabbitmq

  identity-api:
    container_name: identity-api
    image: identity-api:1.0.0
    depends_on:
      - psql
      - rabbitmq
    env_file:
      - .enviroments/identity-api.env

  payment-api:
    container_name: payment-api
    image: payment-api:1.0.0
    depends_on:
      - psql
      - rabbitmq

  promocode-api:
    container_name: promocode-api
    image: promocode-api:1.0.0
    depends_on:
      - psql
      - rabbitmq

  resources-api:
    container_name: resources-api
    image: resources-api:1.0.0
    depends_on:
      - psql
      - rabbitmq

  review-api:
    container_name: review-api
    image: review-api:1.0.0
    depends_on:
      - psql
      - rabbitmq

  statistics-api:
    container_name: statistics-api
    image: statistics-api:1.0.0
    depends_on:
      - psql
      - rabbitmq

  support-api:
    container_name: support-api
    image: support-api:1.0.0
    depends_on:
      - psql
      - rabbitmq

  withdraw-api:
    container_name: withdraw-api
    image: withdraw-api:1.0.0
    depends_on:
      - psql
      - rabbitmq

  gateway-api:
    container_name: gateway-api
    image: gateway-api:1.0.0

volumes:
  database:
  rabbitmq:
