version: "1.0.0"
services:
  nginx:
    image: nginx
    container_name: fileserver
    hostname: fileserver
    restart: always
    volumes:
      - ./../fileserver:/static/images
      - ./../nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:8080"

  nosqldata:
    image: mongo
    hostname: mongodb
    restart: always
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    expose:
      - "5672"
      - "15672"
    volumes:
      - rabbitmq:/rabbitmq
    ports:
      - "15672:15672"

  psql: 
    image: postgres:13.3
    hostname: psql
    container_name: psql
    restart: always
    command: postgres -c 'max_connections=200'
    stdin_open: true
    tty: true
    env_file:
      - pg.env
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  auth-api: 
    image: "auth-api"
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: Services/Authentication/Authentication.API/Dockerfile
    env_file:
      - .env
    depends_on:
      - psql
      - rabbitmq
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID_AUTH:/root/.microsoft/usersecrets/$USER_SECRETS_ID_AUTH:ro
      - ./../fileserver:/static/images
    ports:
      - "5033:8080"

  email-api:
    image: "email-api"
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: Services/EmailSender/EmailSender.API/Dockerfile
    env_file:
      - .env
    depends_on:
      - psql
      - rabbitmq
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID_EMAIL:/root/.microsoft/usersecrets/$USER_SECRETS_ID_EMAIL:ro
      - ./../fileserver:/static/images
    ports:
      - "5225:8080"

  game-api:
    image: "game-api"
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: Services/Game/Game.API/Dockerfile
    env_file:
      - .env
    depends_on:
      - psql
      - rabbitmq
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID_GAME:/root/.microsoft/usersecrets/$USER_SECRETS_ID_GAME:ro
      - ./../fileserver:/static/images
    ports:
      - "5184:8080"

  identity-api:
    image: "identity-api"
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    env_file:
      - .env
    depends_on:
      - psql
      - rabbitmq
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID_IDENTITY:/root/.microsoft/usersecrets/$USER_SECRETS_ID_IDENTITY:ro
      - ./../fileserver:/static/images
    ports:
      - "5259:8080"

  payment-api:
    image: "payment-api"
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile
    env_file:
      - .env
    depends_on:
      - psql
      - rabbitmq 
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID_PAYMENT:/root/.microsoft/usersecrets/$USER_SECRETS_ID_PAYMENT:ro
      - ./../fileserver:/static/images
    ports:
      - "5039:8080"

  promocode-api:
    image: "promocode-api"
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: Services/Promocode/Promocode.API/Dockerfile
    env_file:
      - .env
    depends_on:
      - psql
      - rabbitmq 
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID_PROMOCODE:/root/.microsoft/usersecrets/$USER_SECRETS_ID_PROMOCODE:ro
      - ./../fileserver:/static/images
    ports:
      - "5163:8080"

  resources-api:
    image: "resources-api"
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: Services/Resources/Resources.API/Dockerfile
    env_file:
      - .env
    depends_on:
      - psql
      - rabbitmq 
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID_RESOURCES:/root/.microsoft/usersecrets/$USER_SECRETS_ID_RESOURCES:ro
      - ./../fileserver:/static/images
    ports:
      - "5073:8080"

  review-api:
    image: "review-api"
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: Services/Review/Review.API/Dockerfile
    env_file:
      - .env
    depends_on:
      - psql
      - rabbitmq 
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID_REVIEW:/root/.microsoft/usersecrets/$USER_SECRETS_ID_REVIEW:ro
      - ./../fileserver:/static/images
    ports:
      - "5079:8080"

  statistics-api:
    image: "statistics-api"
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: Services/Statistics/Statistics.API/Dockerfile
    env_file:
      - .env
    depends_on:
      - psql
      - rabbitmq
      - nosqldata
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID_STATISTICS:/root/.microsoft/usersecrets/$USER_SECRETS_ID_STATISTICS:ro
      - ./../fileserver:/static/images
    ports:
      - "5231:8080"

  support-api:
    image: "support-api"
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: Services/Support/Support.API/Dockerfile
    env_file:
      - .env
    depends_on:
      - psql
      - rabbitmq 
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID_SUPPORT:/root/.microsoft/usersecrets/$USER_SECRETS_ID_SUPPORT:ro
      - ./../fileserver:/static/images
    ports:
      - "5155:8080"

  withdraw-api:
    image: "withdraw-api"
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: Services/Withdraw/Withdraw.API/Dockerfile
    env_file:
      - .env
    depends_on:
      - psql
      - rabbitmq 
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID_WITHDRAW:/root/.microsoft/usersecrets/$USER_SECRETS_ID_WITHDRAW:ro
      - ./../fileserver:/static/images
    ports:
      - "5187:8080"

  gateway-api:
    image: "gateway-api"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTPS_PORT: "5000"
      ASPNETCORE_URLS: https://+:443;http://+:8080
      ASPNETCORE_Kestrel__Certificates__Default__Password: password 
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    build:
      context: .
      dockerfile: InCase.ApiGateway/Dockerfile
    env_file:
      - .env
    ports:
      - "5000:443"
      - "5001:8080"
    volumes:
      - ~/.aspnet/https:/https:ro


volumes:
  database:
  rabbitmq: