name: .Net 8 Microservices Tests

on:
  push:
    branches: [ "InCase.dev", "InCase.prod" ]
  pull_request:
    branches: [ "InCase.dev", "InCase.prod" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Tests Game.UAT
      run: |
            cd src/InCase/Services/Game/Game.UAT
            dotnet test