name: Verify type labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  verify-type-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: zwaldowski/match-label-action@v2
        with:
          allowed: type:feature, type:HOT FIX, type:FIX, type:enhancement, type:documentation, type:HELP